AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
  using Amazon API Gateway.
Parameters:
  TableNameParameter:
    Type: String
Globals:
  Function:
    Runtime: python3.6
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: s3://abehrens-sam-deployment-bucket/50f419cd5dd223751f6493e5386cb06c
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      Timeout: 10
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableNameParameter
      Events:
        HelloWorldEvent:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
  Table:
    Type: AWS::Serverless::SimpleTable
