AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (with to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Globals:
  Function:
    Runtime: python3.6
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: s3://abehrens-sam-deployment-bucket/673b651ddb5fba213e7c77ac27de1f44
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
          REGION_NAME:
            Ref: AWS::Region
      Policies:
      - DynamoDBCrudPolicy:
          TableName: Shooter
      Events:
        HelloWorldEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: ANY
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Shooter
